### ISSUE TITLE
Enable HTTPS on html5boilerplate.com

### ISSUE THREAD

**Issue by davidmurdoch** [h5bp/html5boilerplate.com#124]
This *can* be as easy as switching DNS hosts to CloudFlare, which is free (though the free version doesn't support people on Windows XP) and may prevent issues like #1606 from happening again.

While h5bp.com doesn't actually serve anything that absolutely needs to be encrypted, it would prevent attacks like POODLE, which rely on plaintext HTTP connections to work, from being piggybacking on h5bp.com.

**Comment by paulirish** [comment]
We're looking good  with SSL now.

![image](https://cloud.githubusercontent.com/assets/39191/5696791/758b1e2a-9991-11e4-9fe1-2e9e689da99a.png)

https://www.ssllabs.com/ssltest/analyze.html?d=html5boilerplate.com&s=104.28.12.86

Cloudflare is our HTTPS frontend here. It is not full security as the origin host doesn't have SSL, but that isn't a huge issue for us, IMO.

https://support.cloudflare.com/hc/en-us/articles/200170416-What-do-the-SSL-options-Off-Flexible-SSL-Full-SSL-Full-SSL-Strict-mean-

![image](https://cloud.githubusercontent.com/assets/39191/5696797/a6d09532-9991-11e4-80c8-ac05f0d72e1e.png)

**Comment by paulirish** [comment]
@arthurvr will be putting in the redirect and this'll be totally complete

<hr>

if you want to check it out now: https://html5boilerplate.com/

**Comment by davidmurdoch** [comment]
\o/, one issue: https://www.html5boilerplate.com redirects to http://html5boilerplate.com

**Comment by paulirish** [comment]
DONE DONE DONE

![image](https://cloud.githubusercontent.com/assets/39191/5766071/5cff3984-9cb3-11e4-8c72-3ce73a33c49f.png)


redirect is set up. we used a cloudflare "pagerule" for  "always http" and it was a piece of cake. We'll be using that instead of apache hackery.

Thanks for proposing this @davidmurdoch and for everyone's help!

**Comment by arthurvr** [comment]
Thanks @paulirish!
