### ISSUE TITLE
Link to docs incorrect (404)

### ISSUE THREAD

**Issue by tedyoung** [h5bp/html5boilerplate.com#183]
**I'm submitting a ...**

- [X] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (below))

The `Docs` link in the header of the index.html (home) page takes you to https://github.com/h5bp/html5-boilerplate/blob/6.1.0/dist/doc/TOC.md, but it should take you to https://github.com/h5bp/html5-boilerplate/blob/v6.1.0/dist/doc/TOC.md.

The difference is the missing `v` in front of the version number (since `v6.1.0` is the tag name, not `6.1.0`).

I'd submit a pull request to fix the `package.json`, but I wasn't sure how that'd affect anything else that might rely on the version number, hence this issue. 😄

**Comment by roblarsen** [comment]
Thanks @tedyoung! I'm an idiot because I didn't document the release process and screwed up two separate conventions with the tag. Everything is automated, but not foolproof and I was the fool today 👍
