### ISSUE TITLE
Move HTML5Boilerplate.com to gh-pages

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5boilerplate.com#184]
I have the power!

**Comment by coliff** [comment]
There's a `new-build-process` branch which is in pretty good shape. when you run the build process it outputs to the 'docs' dir which the site can be hosted from.

**Comment by coliff** [comment]
we're live on GitHub Pages!

**Comment by roblarsen** [comment]
🚀

**Comment by roblarsen** [comment]
thanks @paulirish for 15 minutes of ⌨️ magic.
