### ISSUE TITLE
Add <meta name="theme-color" content="#E08524">

### ISSUE THREAD

**Issue by coliff** [h5bp/html5boilerplate.com#190]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

To match the main repo we recommend to add <meta name="theme-color" content=""> to the HTML. The color should match as what is defined in the web manifest, in this case #E08524

**Comment by coliff** [comment]
I'll open a PR for this today

**Comment by roblarsen** [comment]
👍

**Comment by coliff** [comment]
Fixed in #195
