### ISSUE TITLE
Add OpenGraph meta tags

### ISSUE THREAD

**Issue by coliff** [h5bp/html5boilerplate.com#201]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

## Notes:

It'd be good to add opengraph meta tags so sharing the URL on Facebook and other platforms will give a rich preview including icon. You can test now at:
- https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fhtml5boilerplate.com
- https://opengraphcheck.com/result.php?url=https%3A%2F%2Fhtml5boilerplate.com

**Comment by roblarsen** [comment]
💯
