### ISSUE TITLE
Upgrade gulp to 4.0 and upgrade gulpfile to be compatible with new version (or something!)

### ISSUE THREAD

**Issue by coliff** [h5bp/html5boilerplate.com#209]
The build script here is using Gulp 3.9.1. It'd be good to get this updated to Gulp 4.x. Many gulp plugins require Gulp 4.x now.

**Comment by kyds3k** [comment]
Any update on this? @coliff did you find a solution?

**Comment by roblarsen** [comment]
@kyds3k Help is still wanted.

**Comment by coliff** [comment]
Actually, I think we can do away with Gulp altogether and have all the required scripts done with npm/node scripts and/or use [Parcel ](https://parceljs.org/) like we'll do with html5 boilerplate.

**Comment by roblarsen** [comment]
💯 I was thinking about that. It would be nice to move to something I was more familiar with, to be honest. I have only ever used Gulp on this project.

**Comment by coliff** [comment]
thanks for fixing @roblarsen ! 🍻
