### ISSUE TITLE
Update Google Analytics and Analyze Custom GA Code in the Site Script File

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5boilerplate.com#279]

**Comment by coliff** [comment]
What shall we do about this? No point in adding back Universal Analytics with it being end of life now… and GA4 does a lot of the auto-tracking of metrics. I don’t think we have access to the h5bp Google analytics account anyway so we ?

**Comment by coliff** [comment]
I think this can be closed now. GA4 does auto-tracking of downloads, external clicks etc without the need for custom tracking scripts.

**Comment by roblarsen** [comment]
We need to delete some rando code in the JS file. Potentially, just deleting the whole thing, actually.
