### ISSUE TITLE
Adding Onmouseover effect

### ISSUE THREAD

**Issue by srummanf** [h5bp/html5boilerplate.com#326]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

## Feature requests

Feature requests are welcome. But take a moment to find out whether your idea
fits with the scope and aims of the project. It's up to *you* to make a strong
case to convince the project's developers of the merits of this feature. Please
provide as much detail and context as possible.

I wanted to add onmouseover effect on the companies which uses Boilerplate from grayscale to color. This UI is being used many a websites these days

**Comment by coliff** [comment]
I think this could be a good idea if the logos were links to the sites, but as they aren't I think it may not be such a good idea from a UX perspective... as I think them changing color may indicate to the user that they are interactive. Thanks for the suggestion though!
