### ISSUE TITLE
GitHub Actions: Deprecating save-state and set-output commands

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5boilerplate.com#327]
Broken builds!

**Comment by roblarsen** [comment]
[GitHub Actions: Deprecating save\-state and set\-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by coliff** [comment]
I think we can just remove this line?

https://github.com/h5bp/html5boilerplate.com/blob/main/.github/workflows/build.yaml#L22

**Comment by roblarsen** [comment]
👍
