### ISSUE TITLE
Remove normalize CSS from homepage and from npm package (don't use it on the site)

### ISSUE THREAD

**Issue by coliff** [h5bp/html5boilerplate.com#369]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

**Comment by Gowrish7** [comment]
Hey Coliff i would like to work on this issue can you give me a detailed desc of how to remove Modernizr CSS from npm package  ?

**Comment by Gowrish7** [comment]
> Hi @Gowrish7 writing up a detailed description would take more time than actually doing the work
Hello @roblarsen can you check whether this is proper ? 
![image](https://github.com/h5bp/html5boilerplate.com/assets/103709921/633ec65b-8856-45b3-b060-026f2b28cc2a)

**Comment by roblarsen** [comment]
@Gowrish7 that's a screen shot

**Comment by roblarsen** [comment]
@coliff I don't see anything in packagejson or a "no-js" class in the HTML file. Am i missing something?

**Comment by coliff** [comment]
Oops, my mistake with the issue title. It should be remove normalize (not modernizr)
